/**
 * Role default permissions + full catalog for Super Admin checklist.
 * Keep PERMISSION_GROUPS in sync with frontend/src/constants/permissions.js.
 */
const permissions = {
  'Super Admin': ['*'],
  'Admin': [
    'VIEW_DASHBOARD',
    'VIEW_PATIENT', 'CREATE_PATIENT', 'UPDATE_PATIENT', 'VIEW_PATIENT_PROFILE', 'UPDATE_PATIENT_PROFILE',
    'VIEW_OP_QUEUE', 'CREATE_OP_QUEUE', 'UPDATE_OP_QUEUE',
    'VIEW_APPOINTMENT', 'CREATE_APPOINTMENT', 'UPDATE_APPOINTMENT', 'CANCEL_APPOINTMENT', 'VIEW_QUEUE_DISPLAY',
    'CREATE_CONSULTATION', 'VIEW_PRESCRIPTION', 'CREATE_SERVICE_USAGE',
    'VIEW_IP_ADMISSION', 'CREATE_IP_ADMISSION', 'UPDATE_IP_ADMISSION', 'PROCESS_DISCHARGE',
    'VIEW_NURSE_STATION', 'RECORD_VITALS', 'SHIFT_HANDOVER', 'MANAGE_DOCTOR_ORDERS',
    'VIEW_BILLING', 'CREATE_BILLING', 'UPDATE_BILLING', 'PAY_BILL', 'CANCEL_BILL', 'VIEW_BILLING_REPORTS', 'VIEW_PENDING_DISCHARGE',
    'VIEW_PHARMACY', 'MANAGE_PHARMACY', 'CREATE_MEDICINE', 'EDIT_MEDICINE', 'ADD_PHARMACY_STOCK',
    'ADJUST_PHARMACY_STOCK', 'EDIT_PHARMACY_BATCH', 'DELETE_MEDICINE', 'MANAGE_SUPPLIERS', 'VIEW_EXPIRY_REPORT', 'DISPENSE_PRESCRIPTION',
    'VIEW_LAB', 'CREATE_LAB_ORDER', 'UPDATE_LAB_ORDER', 'UPDATE_LAB_REPORT', 'PRINT_LAB_REPORT', 'MANAGE_LAB_TESTS',
    'VIEW_BEDS', 'MANAGE_BEDS', 'CREATE_BED', 'UPDATE_BED', 'DELETE_BED', 'UPDATE_BED_STATUS', 'MANAGE_ROOMS', 'MANAGE_WARDS',
    'VIEW_DEPARTMENTS', 'MANAGE_DEPARTMENTS',
    'VIEW_ASSETS', 'MANAGE_ASSETS', 'CREATE_ASSET', 'UPDATE_ASSET', 'DELETE_ASSET',
    'VIEW_ASSET_COMPLAINTS', 'CREATE_ASSET_COMPLAINT', 'UPDATE_ASSET_COMPLAINT', 'MANAGE_ASSET_COMPLAINTS',
    'VIEW_BEMS', 'MANAGE_BEMS', 'VIEW_BEMS_REPORTS',
    'VIEW_STAFF', 'CREATE_STAFF', 'UPDATE_STAFF', 'MANAGE_STAFF',
    'VIEW_REPORTS', 'VIEW_ACTIVITY', 'EXPORT_REPORTS',
    'MANAGE_MASTERS', 'MANAGE_SETTINGS', 'MANAGE_BRANDING', 'MANAGE_SERVICES',
    'CREATE_CHANGE_REQUEST', 'VIEW_CHANGE_REQUESTS', 'REVIEW_CHANGE_REQUESTS',
    'VIEW_CHAT', 'VIEW_NOTIFICATIONS',
  ],
  'Doctor': [
    'VIEW_DASHBOARD',
    'VIEW_PATIENT', 'VIEW_PATIENT_PROFILE', 'UPDATE_PATIENT_PROFILE',
    'VIEW_OP_QUEUE', 'CREATE_CONSULTATION', 'UPDATE_CONSULTATION',
    'CREATE_PRESCRIPTION', 'VIEW_PRESCRIPTION', 'CREATE_SERVICE_USAGE',
    'VIEW_LAB', 'CREATE_LAB_ORDER',
    'VIEW_IP_ADMISSION', 'UPDATE_IP_ADMISSION', 'CREATE_DISCHARGE_SUMMARY', 'CREATE_DOCTOR_ROUND', 'MANAGE_IP_MEDICATION',
    'VIEW_NURSE_STATION', 'MANAGE_DOCTOR_ORDERS',
    'VIEW_ASSET_COMPLAINTS', 'CREATE_ASSET_COMPLAINT',
    'CREATE_CHANGE_REQUEST', 'VIEW_CHANGE_REQUESTS',
    'VIEW_CHAT', 'VIEW_NOTIFICATIONS',
  ],
  'Receptionist': [
    'VIEW_DASHBOARD',
    'VIEW_PATIENT', 'CREATE_PATIENT', 'UPDATE_PATIENT', 'VIEW_PATIENT_PROFILE',
    'VIEW_OP_QUEUE', 'CREATE_OP_QUEUE', 'UPDATE_OP_QUEUE', 'VIEW_QUEUE_DISPLAY',
    'VIEW_APPOINTMENT', 'CREATE_APPOINTMENT', 'UPDATE_APPOINTMENT', 'CANCEL_APPOINTMENT',
    'CREATE_CONSULTATION', 'CREATE_PRESCRIPTION', 'VIEW_PRESCRIPTION', 'CREATE_SERVICE_USAGE',
    'VIEW_IP_ADMISSION', 'CREATE_IP_ADMISSION', 'PROCESS_DISCHARGE', 'CREATE_DISCHARGE_SUMMARY',
    'VIEW_BILLING', 'CREATE_BILLING', 'PAY_BILL', 'VIEW_PENDING_DISCHARGE',
    'VIEW_LAB', 'CREATE_LAB_ORDER',
    'VIEW_ASSET_COMPLAINTS', 'CREATE_ASSET_COMPLAINT',
    'CREATE_CHANGE_REQUEST', 'VIEW_CHANGE_REQUESTS',
    'VIEW_CHAT', 'VIEW_NOTIFICATIONS',
  ],
  'Pharmacist': [
    'VIEW_DASHBOARD',
    'VIEW_PATIENT',
    'VIEW_PRESCRIPTION', 'DISPENSE_PRESCRIPTION',
    'VIEW_PHARMACY', 'MANAGE_PHARMACY', 'CREATE_MEDICINE', 'EDIT_MEDICINE',
    'ADD_PHARMACY_STOCK', 'ADJUST_PHARMACY_STOCK', 'EDIT_PHARMACY_BATCH', 'MANAGE_SUPPLIERS', 'VIEW_EXPIRY_REPORT',
    'VIEW_BILLING', 'CREATE_BILLING', 'PAY_BILL', 'VIEW_BILLING_REPORTS',
    'VIEW_IP_ADMISSION',
    'VIEW_ASSET_COMPLAINTS', 'CREATE_ASSET_COMPLAINT',
    'CREATE_CHANGE_REQUEST', 'VIEW_CHANGE_REQUESTS',
    'VIEW_CHAT', 'VIEW_NOTIFICATIONS',
  ],
  'Lab Technician': [
    'VIEW_DASHBOARD',
    'VIEW_LAB', 'CREATE_LAB_ORDER', 'UPDATE_LAB_ORDER', 'UPDATE_LAB_REPORT', 'PRINT_LAB_REPORT',
    'VIEW_ASSET_COMPLAINTS', 'CREATE_ASSET_COMPLAINT',
    'CREATE_CHANGE_REQUEST', 'VIEW_CHANGE_REQUESTS',
    'VIEW_CHAT', 'VIEW_NOTIFICATIONS',
  ],
  'Accountant': [
    'VIEW_DASHBOARD',
    'VIEW_PATIENT',
    'VIEW_BILLING', 'CREATE_BILLING', 'UPDATE_BILLING', 'PAY_BILL', 'CANCEL_BILL',
    'VIEW_BILLING_REPORTS', 'VIEW_PENDING_DISCHARGE', 'VIEW_REPORTS',
    'CREATE_CHANGE_REQUEST', 'VIEW_CHANGE_REQUESTS',
    'VIEW_CHAT', 'VIEW_NOTIFICATIONS',
  ],
  'Nurse': [
    'VIEW_DASHBOARD',
    'VIEW_PATIENT', 'CREATE_PATIENT', 'UPDATE_PATIENT', 'VIEW_PATIENT_PROFILE',
    'VIEW_IP_ADMISSION', 'CREATE_NURSING_NOTE', 'CREATE_SERVICE_USAGE', 'MANAGE_IP_MEDICATION',
    'VIEW_NURSE_STATION', 'RECORD_VITALS', 'SHIFT_HANDOVER', 'MANAGE_DOCTOR_ORDERS',
    'UPDATE_BED_STATUS', 'VIEW_BEDS',
    'VIEW_LAB', 'CREATE_LAB_ORDER',
    'VIEW_ASSET_COMPLAINTS', 'CREATE_ASSET_COMPLAINT',
    'CREATE_CHANGE_REQUEST', 'VIEW_CHANGE_REQUESTS',
    'VIEW_CHAT', 'VIEW_NOTIFICATIONS',
  ],
  'Patient': [
    'VIEW_DASHBOARD',
    'VIEW_OWN_APPOINTMENTS',
    'VIEW_OWN_PRESCRIPTIONS',
    'VIEW_OWN_LAB_REPORTS',
    'VIEW_OWN_BILLS',
  ],
  'Biomedical Engineer': [
    'VIEW_DASHBOARD',
    'VIEW_BEMS', 'MANAGE_BEMS', 'VIEW_BEMS_REPORTS',
    'VIEW_ASSETS', 'MANAGE_ASSETS', 'CREATE_ASSET', 'UPDATE_ASSET', 'DELETE_ASSET',
    'VIEW_ASSET_COMPLAINTS', 'CREATE_ASSET_COMPLAINT', 'UPDATE_ASSET_COMPLAINT', 'MANAGE_ASSET_COMPLAINTS',
    'VIEW_ACTIVITY',
    'CREATE_CHANGE_REQUEST', 'VIEW_CHANGE_REQUESTS',
    'VIEW_CHAT', 'VIEW_NOTIFICATIONS',
  ],
};

const PERMISSION_GROUPS = {
  Dashboard: ['VIEW_DASHBOARD'],
  Patients: [
    'VIEW_PATIENT', 'CREATE_PATIENT', 'UPDATE_PATIENT', 'DELETE_PATIENT',
    'VIEW_PATIENT_PROFILE', 'UPDATE_PATIENT_PROFILE',
  ],
  'OP / Appointments': [
    'VIEW_OP_QUEUE', 'CREATE_OP_QUEUE', 'UPDATE_OP_QUEUE',
    'VIEW_APPOINTMENT', 'CREATE_APPOINTMENT', 'UPDATE_APPOINTMENT', 'CANCEL_APPOINTMENT',
    'VIEW_QUEUE_DISPLAY',
  ],
  Consultation: [
    'CREATE_CONSULTATION', 'UPDATE_CONSULTATION',
    'CREATE_PRESCRIPTION', 'VIEW_PRESCRIPTION', 'DISPENSE_PRESCRIPTION',
    'CREATE_SERVICE_USAGE',
  ],
  'IP Admission': [
    'VIEW_IP_ADMISSION', 'CREATE_IP_ADMISSION', 'UPDATE_IP_ADMISSION',
    'PROCESS_DISCHARGE', 'CREATE_DISCHARGE_SUMMARY',
    'CREATE_NURSING_NOTE', 'CREATE_DOCTOR_ROUND', 'MANAGE_IP_MEDICATION',
    'VIEW_NURSE_STATION', 'RECORD_VITALS', 'SHIFT_HANDOVER', 'MANAGE_DOCTOR_ORDERS',
  ],
  Billing: [
    'VIEW_BILLING', 'CREATE_BILLING', 'UPDATE_BILLING', 'PAY_BILL', 'CANCEL_BILL',
    'VIEW_BILLING_REPORTS', 'VIEW_PENDING_DISCHARGE',
  ],
  Pharmacy: [
    'VIEW_PHARMACY', 'MANAGE_PHARMACY', 'CREATE_MEDICINE', 'EDIT_MEDICINE',
    'ADD_PHARMACY_STOCK', 'ADJUST_PHARMACY_STOCK', 'EDIT_PHARMACY_BATCH', 'DELETE_MEDICINE',
    'MANAGE_SUPPLIERS', 'VIEW_EXPIRY_REPORT',
  ],
  Lab: [
    'VIEW_LAB', 'CREATE_LAB_ORDER', 'UPDATE_LAB_ORDER', 'UPDATE_LAB_REPORT',
    'PRINT_LAB_REPORT', 'MANAGE_LAB_TESTS',
  ],
  'Beds, Rooms & Wards': [
    'VIEW_BEDS', 'MANAGE_BEDS', 'CREATE_BED', 'UPDATE_BED', 'DELETE_BED',
    'UPDATE_BED_STATUS', 'MANAGE_ROOMS', 'MANAGE_WARDS',
  ],
  Departments: ['VIEW_DEPARTMENTS', 'MANAGE_DEPARTMENTS'],
  'Assets & Complaints': [
    'VIEW_ASSETS', 'MANAGE_ASSETS', 'CREATE_ASSET', 'UPDATE_ASSET', 'DELETE_ASSET',
    'VIEW_ASSET_COMPLAINTS', 'CREATE_ASSET_COMPLAINT', 'UPDATE_ASSET_COMPLAINT', 'MANAGE_ASSET_COMPLAINTS',
  ],
  Biomedical: [
    'VIEW_BEMS', 'MANAGE_BEMS', 'VIEW_BEMS_REPORTS',
  ],
  'Staff & Access': [
    'VIEW_STAFF', 'CREATE_STAFF', 'UPDATE_STAFF', 'DELETE_STAFF', 'MANAGE_STAFF',
  ],
  'Reports & Activity': ['VIEW_REPORTS', 'VIEW_ACTIVITY', 'EXPORT_REPORTS'],
  'Change Requests': [
    'CREATE_CHANGE_REQUEST', 'VIEW_CHANGE_REQUESTS', 'REVIEW_CHANGE_REQUESTS',
  ],
  'Settings & Masters': [
    'MANAGE_MASTERS', 'MANAGE_SETTINGS', 'MANAGE_BRANDING', 'MANAGE_SERVICES',
  ],
  'Chat & Notifications': ['VIEW_CHAT', 'VIEW_NOTIFICATIONS'],
  'Patient Self-Service': [
    'VIEW_OWN_APPOINTMENTS', 'VIEW_OWN_PRESCRIPTIONS', 'VIEW_OWN_LAB_REPORTS', 'VIEW_OWN_BILLS',
  ],
};

const ALL_PERMISSIONS = Object.values(PERMISSION_GROUPS).flat();

/** Keep only recognized permission codes (or the '*' wildcard) coming from a request body. */
const sanitizePermissions = (input) => {
  if (!Array.isArray(input)) return undefined;
  const cleaned = input.filter((p) => p === '*' || ALL_PERMISSIONS.includes(p));
  return [...new Set(cleaned)];
};

module.exports = permissions;
module.exports.PERMISSION_GROUPS = PERMISSION_GROUPS;
module.exports.ALL_PERMISSIONS = ALL_PERMISSIONS;
module.exports.sanitizePermissions = sanitizePermissions;
