/**
 * Role default permissions + full catalog for Super Admin checklist.
 * Keep PERMISSION_GROUPS in sync with frontend/src/constants/permissions.js.
 */
const permissions = {
  'Super Admin': ['*'],
  'Admin': [
    'VIEW_DASHBOARD',
    'VIEW_PATIENT', 'CREATE_PATIENT', 'UPDATE_PATIENT', 'VIEW_PATIENT_PROFILE', 'UPDATE_PATIENT_PROFILE',
    'VIEW_OP_QUEUE', 'CREATE_OP_QUEUE', 'UPDATE_OP_QUEUE',
    'VIEW_APPOINTMENT', 'CREATE_APPOINTMENT', 'UPDATE_APPOINTMENT', 'CANCEL_APPOINTMENT', 'VIEW_QUEUE_DISPLAY',
    'CREATE_CONSULTATION', 'VIEW_PRESCRIPTION', 'CREATE_SERVICE_USAGE',
    'VIEW_IP_ADMISSION', 'CREATE_IP_ADMISSION', 'UPDATE_IP_ADMISSION', 'PROCESS_DISCHARGE',
    'CREATE_DISCHARGE_SUMMARY', 'CREATE_NURSING_NOTE', 'CREATE_DOCTOR_ROUND', 'MANAGE_IP_MEDICATION',
    'VIEW_NURSE_STATION', 'RECORD_VITALS', 'SHIFT_HANDOVER', 'MANAGE_DOCTOR_ORDERS',
    'VIEW_BILLING', 'CREATE_BILLING', 'UPDATE_BILLING', 'PAY_BILL', 'CANCEL_BILL', 'VIEW_BILLING_REPORTS', 'VIEW_PENDING_DISCHARGE',
    'VIEW_PHARMACY', 'MANAGE_PHARMACY', 'CREATE_MEDICINE', 'EDIT_MEDICINE', 'ADD_PHARMACY_STOCK',
    'ADJUST_PHARMACY_STOCK', 'EDIT_PHARMACY_BATCH', 'DELETE_MEDICINE', 'MANAGE_SUPPLIERS', 'VIEW_EXPIRY_REPORT', 'DISPENSE_PRESCRIPTION',
    'VIEW_LAB', 'CREATE_LAB_ORDER', 'UPDATE_LAB_ORDER', 'UPDATE_LAB_REPORT', 'PRINT_LAB_REPORT', 'MANAGE_LAB_TESTS',
    'VIEW_BEDS', 'MANAGE_BEDS', 'CREATE_BED', 'UPDATE_BED', 'DELETE_BED', 'UPDATE_BED_STATUS', 'MANAGE_ROOMS', 'MANAGE_WARDS',
    'VIEW_DEPARTMENTS', 'MANAGE_DEPARTMENTS',
    'VIEW_ASSETS', 'MANAGE_ASSETS', 'CREATE_ASSET', 'UPDATE_ASSET', 'DELETE_ASSET',
    'VIEW_ASSET_COMPLAINTS', 'CREATE_ASSET_COMPLAINT', 'UPDATE_ASSET_COMPLAINT', 'MANAGE_ASSET_COMPLAINTS',
    'VIEW_BEMS', 'MANAGE_BEMS', 'VIEW_BEMS_REPORTS',
    'VIEW_STAFF', 'CREATE_STAFF', 'UPDATE_STAFF', 'MANAGE_STAFF',
    'VIEW_REPORTS', 'VIEW_ACTIVITY', 'EXPORT_REPORTS',
    'MANAGE_MASTERS', 'MANAGE_SETTINGS', 'MANAGE_BRANDING', 'MANAGE_SERVICES',
    'CREATE_CHANGE_REQUEST', 'VIEW_CHANGE_REQUESTS', 'REVIEW_CHANGE_REQUESTS',
    'VIEW_CHAT', 'VIEW_NOTIFICATIONS',
  ],
  'Doctor': [
    'VIEW_DASHBOARD',
    'VIEW_PATIENT', 'VIEW_PATIENT_PROFILE', 'UPDATE_PATIENT_PROFILE',
    'VIEW_OP_QUEUE', 'CREATE_CONSULTATION', 'UPDATE_CONSULTATION',
    'CREATE_PRESCRIPTION', 'VIEW_PRESCRIPTION', 'CREATE_SERVICE_USAGE',
    'VIEW_LAB', 'CREATE_LAB_ORDER',
    'VIEW_IP_ADMISSION', 'UPDATE_IP_ADMISSION', 'CREATE_DISCHARGE_SUMMARY', 'CREATE_DOCTOR_ROUND', 'MANAGE_IP_MEDICATION',
    'VIEW_NURSE_STATION', 'MANAGE_DOCTOR_ORDERS',
    'VIEW_ASSET_COMPLAINTS', 'CREATE_ASSET_COMPLAINT',
    'CREATE_CHANGE_REQUEST', 'VIEW_CHANGE_REQUESTS',
    'VIEW_CHAT', 'VIEW_NOTIFICATIONS',
  ],
  'Receptionist': [
    'VIEW_DASHBOARD',
    'VIEW_PATIENT', 'CREATE_PATIENT', 'UPDATE_PATIENT', 'VIEW_PATIENT_PROFILE',
    'VIEW_OP_QUEUE', 'CREATE_OP_QUEUE', 'UPDATE_OP_QUEUE', 'VIEW_QUEUE_DISPLAY',
    'VIEW_APPOINTMENT', 'CREATE_APPOINTMENT', 'UPDATE_APPOINTMENT', 'CANCEL_APPOINTMENT',
    'CREATE_CONSULTATION', 'CREATE_PRESCRIPTION', 'VIEW_PRESCRIPTION', 'CREATE_SERVICE_USAGE',
    'VIEW_IP_ADMISSION', 'CREATE_IP_ADMISSION', 'PROCESS_DISCHARGE',
    'VIEW_BILLING', 'CREATE_BILLING', 'UPDATE_BILLING', 'PAY_BILL', 'VIEW_PENDING_DISCHARGE',
    'VIEW_PHARMACY', 'DISPENSE_PRESCRIPTION',
    'VIEW_LAB', 'CREATE_LAB_ORDER',
    'VIEW_ASSET_COMPLAINTS', 'CREATE_ASSET_COMPLAINT',
    'CREATE_CHANGE_REQUEST', 'VIEW_CHANGE_REQUESTS',
    'VIEW_CHAT', 'VIEW_NOTIFICATIONS',
  ],
  'Pharmacist': [
    'VIEW_DASHBOARD',
    'VIEW_PATIENT',
    'VIEW_PRESCRIPTION', 'DISPENSE_PRESCRIPTION',
    'VIEW_PHARMACY', 'MANAGE_PHARMACY', 'CREATE_MEDICINE', 'EDIT_MEDICINE',
    'ADD_PHARMACY_STOCK', 'ADJUST_PHARMACY_STOCK', 'EDIT_PHARMACY_BATCH', 'MANAGE_SUPPLIERS', 'VIEW_EXPIRY_REPORT',
    'VIEW_BILLING', 'CREATE_BILLING', 'UPDATE_BILLING', 'PAY_BILL', 'VIEW_BILLING_REPORTS',
    'VIEW_LAB',
    'VIEW_IP_ADMISSION',
    'VIEW_ASSET_COMPLAINTS', 'CREATE_ASSET_COMPLAINT',
    'CREATE_CHANGE_REQUEST', 'VIEW_CHANGE_REQUESTS',
    'VIEW_CHAT', 'VIEW_NOTIFICATIONS',
  ],
  'Lab Technician': [
    'VIEW_DASHBOARD',
    'VIEW_PATIENT',
    'VIEW_LAB', 'CREATE_LAB_ORDER', 'UPDATE_LAB_ORDER', 'UPDATE_LAB_REPORT', 'PRINT_LAB_REPORT', 'MANAGE_LAB_TESTS',
    'VIEW_ASSET_COMPLAINTS', 'CREATE_ASSET_COMPLAINT',
    'CREATE_CHANGE_REQUEST', 'VIEW_CHANGE_REQUESTS',
    'VIEW_CHAT', 'VIEW_NOTIFICATIONS',
  ],
  'Accountant': [
    'VIEW_DASHBOARD',
    'VIEW_PATIENT',
    'VIEW_BILLING', 'CREATE_BILLING', 'UPDATE_BILLING', 'PAY_BILL', 'CANCEL_BILL',
    'VIEW_BILLING_REPORTS', 'VIEW_PENDING_DISCHARGE', 'VIEW_REPORTS',
    'CREATE_CHANGE_REQUEST', 'VIEW_CHANGE_REQUESTS',
    'VIEW_CHAT', 'VIEW_NOTIFICATIONS',
  ],
  'Nurse': [
    'VIEW_DASHBOARD',
    'VIEW_PATIENT', 'VIEW_PATIENT_PROFILE',
    'VIEW_IP_ADMISSION', 'CREATE_NURSING_NOTE', 'CREATE_SERVICE_USAGE', 'MANAGE_IP_MEDICATION',
    'VIEW_NURSE_STATION', 'RECORD_VITALS', 'SHIFT_HANDOVER', 'MANAGE_DOCTOR_ORDERS',
    'UPDATE_BED_STATUS', 'VIEW_BEDS',
    'VIEW_LAB', 'CREATE_LAB_ORDER',
    'VIEW_ASSET_COMPLAINTS', 'CREATE_ASSET_COMPLAINT',
    'CREATE_CHANGE_REQUEST', 'VIEW_CHANGE_REQUESTS',
    'VIEW_CHAT', 'VIEW_NOTIFICATIONS',
  ],
  'Patient': [
    'VIEW_DASHBOARD',
    'VIEW_OWN_APPOINTMENTS',
    'VIEW_OWN_PRESCRIPTIONS',
    'VIEW_OWN_LAB_REPORTS',
    'VIEW_OWN_BILLS',
  ],
  'Biomedical Engineer': [
    'VIEW_DASHBOARD',
    'VIEW_BEMS', 'MANAGE_BEMS', 'VIEW_BEMS_REPORTS',
    'VIEW_ASSETS', 'MANAGE_ASSETS', 'CREATE_ASSET', 'UPDATE_ASSET', 'DELETE_ASSET',
    'VIEW_ASSET_COMPLAINTS', 'CREATE_ASSET_COMPLAINT', 'UPDATE_ASSET_COMPLAINT', 'MANAGE_ASSET_COMPLAINTS',
    'VIEW_ACTIVITY',
    'CREATE_CHANGE_REQUEST', 'VIEW_CHANGE_REQUESTS',
    'VIEW_CHAT', 'VIEW_NOTIFICATIONS',
  ],
};

const PERMISSION_GROUPS = {
  Dashboard: ['VIEW_DASHBOARD'],
  Patients: [
    'VIEW_PATIENT', 'CREATE_PATIENT', 'UPDATE_PATIENT', 'DELETE_PATIENT',
    'VIEW_PATIENT_PROFILE', 'UPDATE_PATIENT_PROFILE',
  ],
  'OP / Appointments': [
    'VIEW_OP_QUEUE', 'CREATE_OP_QUEUE', 'UPDATE_OP_QUEUE',
    'VIEW_APPOINTMENT', 'CREATE_APPOINTMENT', 'UPDATE_APPOINTMENT', 'CANCEL_APPOINTMENT',
    'VIEW_QUEUE_DISPLAY',
  ],
  Consultation: [
    'CREATE_CONSULTATION', 'UPDATE_CONSULTATION',
    'CREATE_PRESCRIPTION', 'VIEW_PRESCRIPTION', 'DISPENSE_PRESCRIPTION',
    'CREATE_SERVICE_USAGE',
  ],
  'IP Admission': [
    'VIEW_IP_ADMISSION', 'CREATE_IP_ADMISSION', 'UPDATE_IP_ADMISSION',
    'PROCESS_DISCHARGE', 'CREATE_DISCHARGE_SUMMARY',
    'CREATE_NURSING_NOTE', 'CREATE_DOCTOR_ROUND', 'MANAGE_IP_MEDICATION',
    'VIEW_NURSE_STATION', 'RECORD_VITALS', 'SHIFT_HANDOVER', 'MANAGE_DOCTOR_ORDERS',
  ],
  Billing: [
    'VIEW_BILLING', 'CREATE_BILLING', 'UPDATE_BILLING', 'PAY_BILL', 'CANCEL_BILL',
    'VIEW_BILLING_REPORTS', 'VIEW_PENDING_DISCHARGE',
  ],
  Pharmacy: [
    'VIEW_PHARMACY', 'MANAGE_PHARMACY', 'CREATE_MEDICINE', 'EDIT_MEDICINE',
    'ADD_PHARMACY_STOCK', 'ADJUST_PHARMACY_STOCK', 'EDIT_PHARMACY_BATCH', 'DELETE_MEDICINE',
    'MANAGE_SUPPLIERS', 'VIEW_EXPIRY_REPORT',
  ],
  Lab: [
    'VIEW_LAB', 'CREATE_LAB_ORDER', 'UPDATE_LAB_ORDER', 'UPDATE_LAB_REPORT',
    'PRINT_LAB_REPORT', 'MANAGE_LAB_TESTS',
  ],
  'Beds, Rooms & Wards': [
    'VIEW_BEDS', 'MANAGE_BEDS', 'CREATE_BED', 'UPDATE_BED', 'DELETE_BED',
    'UPDATE_BED_STATUS', 'MANAGE_ROOMS', 'MANAGE_WARDS',
  ],
  Departments: ['VIEW_DEPARTMENTS', 'MANAGE_DEPARTMENTS'],
  'Assets & Complaints': [
    'VIEW_ASSETS', 'MANAGE_ASSETS', 'CREATE_ASSET', 'UPDATE_ASSET', 'DELETE_ASSET',
    'VIEW_ASSET_COMPLAINTS', 'CREATE_ASSET_COMPLAINT', 'UPDATE_ASSET_COMPLAINT', 'MANAGE_ASSET_COMPLAINTS',
  ],
  Biomedical: [
    'VIEW_BEMS', 'MANAGE_BEMS', 'VIEW_BEMS_REPORTS',
  ],
  'Staff & Access': [
    'VIEW_STAFF', 'CREATE_STAFF', 'UPDATE_STAFF', 'DELETE_STAFF', 'MANAGE_STAFF',
  ],
  'Reports & Activity': ['VIEW_REPORTS', 'VIEW_ACTIVITY', 'EXPORT_REPORTS'],
  'Change Requests': [
    'CREATE_CHANGE_REQUEST', 'VIEW_CHANGE_REQUESTS', 'REVIEW_CHANGE_REQUESTS',
  ],
  'Settings & Masters': [
    'MANAGE_MASTERS', 'MANAGE_SETTINGS', 'MANAGE_BRANDING', 'MANAGE_SERVICES',
  ],
  'Chat & Notifications': ['VIEW_CHAT', 'VIEW_NOTIFICATIONS'],
  'Patient Self-Service': [
    'VIEW_OWN_APPOINTMENTS', 'VIEW_OWN_PRESCRIPTIONS', 'VIEW_OWN_LAB_REPORTS', 'VIEW_OWN_BILLS',
  ],
};

const ALL_PERMISSIONS = Object.values(PERMISSION_GROUPS).flat();

/**
 * Granting a module (e.g. Nurse Station) must also unlock the supporting
 * actions / lookups that module needs, otherwise Super Admin ticks a box
 * and the page still 403s or hides buttons.
 */
const IMPLIED_PERMISSIONS = {
  VIEW_NURSE_STATION: [
    'VIEW_IP_ADMISSION',
    'VIEW_PATIENT',
    'VIEW_PATIENT_PROFILE',
    'RECORD_VITALS',
    'CREATE_NURSING_NOTE',
    'SHIFT_HANDOVER',
    'MANAGE_IP_MEDICATION',
    'MANAGE_DOCTOR_ORDERS',
    'CREATE_SERVICE_USAGE',
    'CREATE_LAB_ORDER',
    'VIEW_LAB',
    'VIEW_BEDS',
  ],
  VIEW_IP_ADMISSION: ['VIEW_PATIENT'],
  VIEW_BILLING: ['VIEW_PATIENT'],
  VIEW_PENDING_DISCHARGE: ['VIEW_BILLING', 'VIEW_PATIENT'],
  VIEW_PHARMACY: ['VIEW_PATIENT'],
  MANAGE_PHARMACY: ['VIEW_PHARMACY', 'VIEW_PATIENT'],
  VIEW_PRESCRIPTION: ['VIEW_PATIENT'],
  DISPENSE_PRESCRIPTION: ['VIEW_PATIENT', 'VIEW_PRESCRIPTION'],
  VIEW_APPOINTMENT: ['VIEW_PATIENT'],
  VIEW_OP_QUEUE: ['VIEW_PATIENT'],
  CREATE_OP_QUEUE: ['VIEW_PATIENT'],
  CREATE_CONSULTATION: ['VIEW_PATIENT'],
  CREATE_LAB_ORDER: ['VIEW_LAB', 'VIEW_PATIENT'],
  MANAGE_IP_MEDICATION: ['VIEW_IP_ADMISSION', 'VIEW_PATIENT'],
  UPDATE_BILLING: ['VIEW_BILLING'],
  CREATE_BILLING: ['VIEW_BILLING'],
  PAY_BILL: ['VIEW_BILLING'],
  MANAGE_STAFF: ['VIEW_STAFF', 'CREATE_STAFF', 'UPDATE_STAFF', 'DELETE_STAFF'],
  MANAGE_LAB_TESTS: ['VIEW_LAB'],
  MANAGE_BRANDING: ['MANAGE_SETTINGS'],
  CREATE_PRESCRIPTION: ['VIEW_PRESCRIPTION', 'VIEW_PATIENT', 'VIEW_PHARMACY'],
};

const NURSE_STATION_BUNDLE = [
  'VIEW_NURSE_STATION',
  ...IMPLIED_PERMISSIONS.VIEW_NURSE_STATION,
];

const expandEffectivePermissions = (perms) => {
  if (!Array.isArray(perms) || perms.length === 0) return [];
  if (perms.includes('*')) return ['*'];
  const set = new Set(perms);
  let changed = true;
  while (changed) {
    changed = false;
    for (const code of [...set]) {
      const extra = IMPLIED_PERMISSIONS[code];
      if (!extra) continue;
      extra.forEach((implied) => {
        if (!set.has(implied)) {
          set.add(implied);
          changed = true;
        }
      });
    }
  }
  return [...set];
};

const looksLikeFullChecklist = (custom, rolePerms = []) =>
  custom.includes('VIEW_DASHBOARD') ||
  custom.length >= Math.max(10, Math.ceil((rolePerms.length || 10) * 0.5));

/**
 * Resolve what a user can actually do.
 * - Empty custom list → role defaults.
 * - A short extra list (e.g. only Nurse Station) → union with role defaults
 *   so Super Admin grants actually work and pharmacy/billing are not dropped.
 * - A full Staff checklist (has VIEW_DASHBOARD or is large) → use that list
 *   so boxes Super Admin unchecked stay locked.
 */
const resolveEffectivePermissions = (role, stored) => {
  if (role === 'Super Admin') return ['*'];
  const rolePerms = permissions[role] || [];
  const custom = Array.isArray(stored) ? stored.filter(Boolean) : [];
  if (custom.includes('*')) return ['*'];
  if (!custom.length) return expandEffectivePermissions(rolePerms);

  const merged = looksLikeFullChecklist(custom, rolePerms)
    ? custom
    : [...new Set([...rolePerms, ...custom])];
  return expandEffectivePermissions(merged);
};

/** Keep only recognized permission codes (or the '*' wildcard) coming from a request body. */
const sanitizePermissions = (input) => {
  if (!Array.isArray(input)) return undefined;
  const cleaned = input.filter((p) => p === '*' || ALL_PERMISSIONS.includes(p));
  return [...new Set(cleaned)];
};

module.exports = permissions;
module.exports.PERMISSION_GROUPS = PERMISSION_GROUPS;
module.exports.ALL_PERMISSIONS = ALL_PERMISSIONS;
module.exports.IMPLIED_PERMISSIONS = IMPLIED_PERMISSIONS;
module.exports.NURSE_STATION_BUNDLE = NURSE_STATION_BUNDLE;
module.exports.expandEffectivePermissions = expandEffectivePermissions;
module.exports.resolveEffectivePermissions = resolveEffectivePermissions;
module.exports.looksLikeFullChecklist = looksLikeFullChecklist;
module.exports.sanitizePermissions = sanitizePermissions;